### ISSUE TITLE
How to calculate distance along the path to final destination

### ISSUE THREAD

**Issue by akrasuski** [layzerar/recastlib#2]
The result from a query is the path from the origin to the destination. The path consists of a set of points which allows averting obstacles. 
I would like to calculate the distance along this path. It seems trivial, however when the distance is too long the path is limited to the predefined number of points. 
How can I calculate the distance from the origin to the destination regardless of the distance or number of mid-points? 
The problem: There are two exit doors from a building. I would like to find the closest one using recastlib.

**Comment by layzerar** [comment]
You cann't do that. I think you should find the proper value of `maxStraightPath` in your scenario instead.
